name:                smarties
version:             0.1.0.0
github:              "githubuser/smarties"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/smarties#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- QuickCheck
- random
- lens
- MonadRandom
- monadplus

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
#- -Werror

default-extensions:
- InstanceSigs
- LambdaCase
- GADTs
- TupleSections
- ScopedTypeVariables

library:
  source-dirs: src
  exposed-modules:     
    - Smarties
    - Smarties2

executables:
  smarties-example:
    main:                ExampleMain.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smarties

tests:
  smarties-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smarties
